iam_ssoe:
  client_cert_path: ~
  client_key_path: ~
  client_id: 'Mobile_App_API_Server_LOWERS'
  # oauth (rest) and sts (soap) services are on different hosts
  oauth_url: "https://int.fed.eauth.va.gov:444"
  sts_url: "https://preprod.services.eauth.va.gov:9301"
  mock_oauth: true

emis:
  mock: true
  host: https://vaausvrsapp81.aac.va.gov
  veteran_status_url: /VIERSService/eMIS/v1/VeteranStatusService
  payment_url:
    v1: /VIERSService/eMIS/v1/PaymentService
    v2: /VIERSService/eMIS/v2/PaymentService
  military_information_url:
    v1: /VIERSService/eMIS/v1/MilitaryInformationService
    v2: /VIERSService/eMIS/v2/MilitaryInformationService
  client_cert_path: /fake/client/cert/path
  client_key_path: /fake/client/key/path
  soap_namespaces:
    xmlns:xsd: http://www.w3.org/2001/XMLSchema
    xmlns:xsi: http://www.w3.org/2001/XMLSchema-instance
    xmlns:soap: http://www.w3.org/2003/05/soap-envelope
    xmlns:v1: http://viers.va.gov/cdi/CDI/commonService/v1
    xmlns:v12: http://viers.va.gov/cdi/eMIS/RequestResponse/v1
    xmlns:v13: http://viers.va.gov/cdi/eMIS/commonService/v1
  military_information:
    v1:
      soap_namespaces:
        xmlns:v11: http://viers.va.gov/cdi/eMIS/RequestResponse/MilitaryInfo/v1
    v2:
      soap_namespaces:
        xmlns:v1: http://viers.va.gov/cdi/CDI/commonService/v2
        xmlns:v12: http://viers.va.gov/cdi/eMIS/RequestResponse/v2
        xmlns:v13: http://viers.va.gov/cdi/eMIS/commonService/v2
        xmlns:v11: http://viers.va.gov/cdi/eMIS/RequestResponse/MilitaryInfo/v2
  payment:
    v1:
      soap_namespaces:
        xmlns:v11: http://viers.va.gov/cdi/eMIS/RequestResponse/Payment/v1
    v2:
      soap_namespaces:
        xmlns:v1: http://viers.va.gov/cdi/CDI/commonService/v2
        xmlns:v12: http://viers.va.gov/cdi/eMIS/RequestResponse/v2
        xmlns:v13: http://viers.va.gov/cdi/eMIS/commonService/v2
        xmlns:v11: http://viers.va.gov/cdi/eMIS/RequestResponse/Payment/v2
  veteran_status:
    soap_namespaces:
      xmlns:v11: http://viers.va.gov/cdi/eMIS/RequestResponse/VetStatus/v1

evss:
  prefill: true
  url: https://csraciapp6.evss.srarad.com
  service_name: "wss-form526-services-web"
  alternate_service_name: "wss-form526-services-web-v2"
  cert_path: ~
  key_path: ~
  root_cert_path: ~
  versions:
    claims: 3.6
    common: 11.6
    documents: 3.7
  s3:
    uploads_enabled: false
    aws_access_key_id: EVSS_S3_AWS_ACCESS_KEY_ID_XYZ
    aws_secret_access_key: EVSS_S3_AWS_SECRET_ACCESS_KEY_XYZ
    bucket: evss_s3_bucket
    region: evss_s3_region
  disability_compensation_form:
    timeout: 55 # ~1 minute
    submit_timeout: 355 # ~6 minutes
  letters:
    url: https://csraciapp6.evss.srarad.com
    timeout: 55
  ppiu:
    timeout: 30
  pciu:
    timeout: 30
  pciu_address:
    timeout: 30
  mock_claims: true
  mock_letters: true
  mock_gi_bill_status: true
  mock_pciu: true
  mock_pciu_address: true
  mock_ppiu: true
  mock_reference: true
  mock_itf: true
  mock_disabilities_form: true
  mock_common_service: true
  mock_vso_search: true
  aws:
    url: http://fake.evss-reference-data-service.dev/v1
    cert_path: ~
    key_path: ~
    root_ca: ~
  reference_data_service:
    enabled: false
  international_postal_codes: "config/evss/international_postal_codes.json"

va_mobile:
  url: "https://veteran.apps.va.gov"
  mock: true
  key_path: /fake/client/key/path
  timeout: 15

vet360:
  url: "https://int.vet360.va.gov"
  contact_information:
    cache_enabled: false
    enabled: true
    timeout: 30
    mock: true
  address_validation:
    hostname: "sandbox-api.va.gov"
    api_key: "<AV_KEY>"
